steps:
  - name: gcr.io/cloud-builders/go:1.20
    args:
      - install
      - github.com/gohugoio/hugo@v0.111.3
    volumes:
      - path: /go/bin
        name: gobin
  - name: gcr.io/cloud-builders/go:1.20
    script: |
      #!/bin/sh
      set -e
      cd /workspace/dndev 
      /go/bin/hugo # builds to ./public
    volumes:
      - path: /go/bin
        name: gobin
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    args: [ 'gsutil', 'rsync', '-r',
            '/workspace/dndev/public',
            'gs://drornir.dev' ]
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'GOPATH=/go'
