steps:
  - name: gcr.io/cloud-builders/git
    args: [ 'submodule', 'update', '--init', '--recursive' ]
  - name: gcr.io/cloud-builders/go:1.20
    script: |
      #!/bin/sh
      set -e
      cd /workspace/dndev
      
      echo "go install"
      go install github.com/gohugoio/hugo@v0.111.3
      
      /go/bin/hugo
      echo 'ls "$(pwd)/public"'
      ls "$(pwd)/public"
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    args: [ 'gsutil', '-m', 'rsync', '-r',
            '/workspace/dndev/public',
            'gs://drornir.dev' ]
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'GOPATH=/go'
